### ISSUE TITLE
Life.hs

### ISSUE THREAD

**Issue by bputersznit** [BartoszMilewski/GameOfLife#1]
Somewhat of a GHCI noob, but I took a crack at your Life.hs program, but it rudely spat back (see below).
Thoughts as to what must be done?
Regards,
Bernard Putersznit.

bernard@bernard-MS-7823:~/haskell$ ghci Life.hs
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling Life             ( Life.hs, interpreted )

Life.hs:4:1: error:
    Failed to load interface for ‘Control.Comonad’
    Perhaps you meant Control.Monad (from base-4.9.1.0)
    Use -v to see a list of the files searched for.
Failed, modules loaded: none.
Prelude>

**Comment by bputersznit** [comment]
PS: I am absolutely ADORING your Category Theory videos. Finally the subject makes some sense to me. Keep up the great work, I for one am DEEPLY appreciative of your lucidity and enthusiasm.

**Comment by BartoszMilewski** [comment]
You must be missing this library in your installation.

**Comment by bputersznit** [comment]
yep silly me to think ghci would come with it installed - a quick 'cabal install comonad' after a 'cabal update' - thanks.
